version: 2

models:
  - name: taxi_ride_raw
    description: "A data model that combining NYC yellow trip data from 2024"
    columns:
      - name : VendorID
        description : |
          A code indicating the TPEP provider that provided the record. 
          1= Creative Mobile Technologies, LLC
          2= VeriFone Inc.
      - name : tpep_pickup_datetime
        description : "The date and time when the meter was engaged."
      - name : tpep_dropoff_datetime
        description : "The date and time when the meter was disengaged."
      - name : passenger_count
        description : "The number of passengers in the vehicle, this is the driver vehicle"
      - name : Trip_distance
        description : "The elapsed trip distance in miles reported by the taximeter."
      - name : PULocationID
        description : "TLC Taxi Zone in which the taximeter was engaged"
      - name : DOLocationID
        description : "TLC Taxi Zone in which the taximeter was disengaged"
      - name : RateCodeID
        description : | 
          The final rate code in effect at the end of the trip. 
          1 = Standard rate
          2 = JFK
          3 = Newark
          4 = Nassau or Westchester
          5 = Negotaited fare
          6 = Group ride"
      - name : store_and_fwd_flag
        description : "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor"
      - name : payment_type
        description : |
          A numeric code signifying how the passenger paid for the trip.
          1=Credit card
          2=Cash
          3=No charge
          4=Dispute
          5=Unknown
          6=Voided trip
      - name : fare_amount
        description : "The time-and-distance fare calculated by the meter."
      - name : extra
        description : "Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges."
      - name : mta_tax
        description : "$0.50 MTA tax that is automatically triggered based on the metered rate in use."
      - name : improvement_surcharge
        description : "$0.30 improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015."
      - name : tip_amount
        description : "Tip amount – This field is automatically populated for credit card tips. Cash tips are not included."
      - name : tolls_amount
        description : "The total amount charged to passengers. Does not include cash tips."
      - name : congestion_Surcharge
        description : "Total amount collected in trip for NYS congestion surcharge."
      - name : Airport_fee
        description : "$1.25 for pick up only at LaGuardia and John F. Kennedy Airports"

source:
  - name : raw
    description : "Raw NYC taxi data"
    tables:
      - name : yellow_taxi_2024
        description : "NYC Yellow Taxi trip data for year 2024"